spring.application.name=hate-speech-detector
gemini.key= AQ.Ab8RN6INac3jxYBn2qdfERXFiOmbA1VMkCThXXbWOUZ3ZkZHdA
gemini.model= gemini-3.1-flash-lite
gemini.url= https://generativelanguage.googleapis.com/v1beta/models
gemini.batch-size= 10
gemini.max-retries= 3